### ISSUE TITLE
multi requests have no path associated, so no stats can be associated

### ISSUE THREAD

**Issue by rgs1** [twitter/zktraffic#17]
We currently parse Multi requests but we don't associate any path to it, so there's no per path stats for Multi. Given that Multi, by definition, is about multiple paths and that we can't extract all paths (ZKTraffic only looks at the first packet, not at the whole stream, for efficiency) it might be alright to account the Multi request to the path of the first request inside it, i.e.:

```
Multi(Create(/foo), Create(/foo/bar), Delete(/foo/bar))
```

would be counted as (Multi, /foo) in the stats.

**Comment by Yasumoto** [comment]
Could you have a `Multi(Create(/foo), Create(/bar))` ?

**Comment by rgs1** [comment]
you could, but we wouldn't necessarily be able to see it (i.e.: if it expands to more than 1 IP packet, highly likely).

**Comment by rgs1** [comment]
https://github.com/twitter/zktraffic/pull/26

**Comment by rgs1** [comment]
this is partially solved, since we expose the first path in the txn. good enough for now, i guess.
