### ISSUE TITLE
unhandled exceptions in zktraffic/base/sniffer.py handle_packet

### ISSUE THREAD

**Issue by bensherman** [twitter/zktraffic#59]
in sniffer.py, if there are exceptions that aren't specifically called out, the daemon just quits without logging anything.  I'm specifically seeing StringTooLong exceptions, but there may be others.

It looks like this was addressed in omni_sniffer, catching any other exceptions in the handle_packet method:

``` python
    except Exception as ex:
      print("got: %s" % str(ex))
      hexdump.hexdump(packet.load)
      traceback.print_exc()
      sys.stdout.flush()
```

We are working on a fix, but it may take some time here to put together a pull request.

**Comment by Yasumoto** [comment]
Good catch @bensherman! Reach out to myself or @rgs1 with questions on the PR- I assume you're working on this?

**Comment by bensherman** [comment]
Pull request added!
